### ISSUE TITLE
Allow buying and selling more than 1 of item

### ISSUE THREAD

**Issue by Lerke** [Agadar/DankTimesBot-Plugin-Items#1]
Buying stonks as a real rich boi now requires big spam. I propose buying more than one stonk when an additional second parameter is provided.

/buy stonks => buys 1 stonk if possible, else error
/buy stonks 10 => buys 10 stonk if possible, else error

**Comment by bart-kneepkens** [comment]
This looks promising! 🚀

**Comment by Agadar** [comment]
Added in df9560eca921b5c764a57dd018f329fc6d805ddc.
