### ISSUE TITLE
Add the option to /identify an entire shop/inventory

### ISSUE THREAD

**Issue by TomChermin** [Agadar/DankTimesBot-Plugin-Items#13]
It would be nice if after a /shop one could reply to the bot message with /identify to immediately identify the entire shop. This would be great for inventory and equipment as well

**Comment by Agadar** [comment]
I'll check if this doesn't easily result in Telegram errors due to long messages or spam vibes in general due to inventory/shop sizes.

**Comment by Agadar** [comment]
I think this will be solved by https://github.com/Agadar/DankTimesBot-Plugin-Items/issues/21, what do you think?
