### ISSUE TITLE
Add /equip full set

### ISSUE THREAD

**Issue by rbrants** [Agadar/DankTimesBot-Plugin-Items#15]
For example /equip pious to equip every pious item in your inventory

**Comment by Agadar** [comment]
As in, allowing users to create/edit/remove entire sets? Or just equipping all items of a specific type e.g. pious?

**Comment by rbrants** [comment]
Allow a user to equip all the pious items in his inventory with 1 command

**Comment by Agadar** [comment]
Should go hand in hand with #3.

**Comment by Agadar** [comment]
Implemented in b3b552d.
