### ISSUE TITLE
Add a mount slot to equip items into (like horses)

### ISSUE THREAD

**Issue by Corpelijn** [Agadar/DankTimesBot-Plugin-Items#16]

**Comment by Agadar** [comment]
Maybe allow item packs to register their own equipment slots?

**Comment by Agadar** [comment]
This needs more details. Should item packs be able to add their own equipment slots? If so, any suggestions how this should be implemented? Furthermore, for this particular case, what will the mount slot do? What items are allowed and what do the items do?
